version: '3'

services:
  reverse-proxy:
    image: traefik:v2.3
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:13.0
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: halp

  backend:
    image: node:14.12.0
    expose:
      - 4000
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: halp
    command: yarn workspace backend dev
    volumes:
      - .:/opt/app/backend:rw
    working_dir: /opt/app/backend
    labels:
      - "traefik.http.routers.backend.rule=Host(`halp.localhost`) && PathPrefix(`/graphql`)"

  frontend:
    build: ./packages/frontend
    expose:
      - 80
    volumes:
      - ./packages/frontend:/opt/app
      - node_modules:/opt/app/node_modules
    labels:
      - "traefik.http.routers.frontend.rule=Host(`halp.localhost`)"

volumes:
  node_modules:
